- name: Deploy Docker
  hosts: nana-test
  become: yes
  become_user: student
  tasks:
    - name: install Docker's additional files
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present
        update_cache: no

    - name: add docker's gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: cleaning cache
      shell: "sudo apt-get -y clean && sudo apt-get -y autoclean"

    - name: add docker in repository
      shell: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"'
      ignore_errors: True

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
